name: Java Maven release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
          server-id: github
      - name: Configure Git user
        run: |
          echo $GITHUB_ACTOR
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Prepare release with Maven
        run: |
          ./mvnw \
            --debug \
            --batch-mode \
            --update-snapshots \
            --file pom.xml \
            -DpushChanges=false \
            release:clean \
            release:prepare \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release with Maven
        run: |
          ./mvnw \
            --debug \
            --batch-mode \
            --update-snapshots \
            --file pom.xml \
            -DlocalCheckout=true \
            -Dmaven.deploy.skip=true \
            release:perform \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Git push changes
        run: |
          git push origin --follow-tags -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
